In [21]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv(r'D:\Study\Kuliah Semester 5\Simulasi A2\Tugas Akhir\Deteksi Fraud.csv')

In [23]:
# Check Distribution
fraud_distribution = df['fraud_bool'].value_counts()
print(fraud_distribution)

0    988971
1     11029
Name: fraud_bool, dtype: int64

In [24]:
fraud_cases = df[df['fraud_bool'] == 1]
non_fraud_cases = df[df['fraud_bool'] == 0]

# 500 Sample for Fraud and 500 Sample for Non-Fraud
fraud_sample = fraud_cases.sample(n=500, random_state=42)
non_fraud_sample = non_fraud_cases.sample(n=500, random_state=42)

# Combining
balanced_df = pd.concat([fraud_sample, non_fraud_sample])
balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Check
print(balanced_df['fraud_bool'].value_counts())

0    500
1    500
Name: fraud_bool, dtype: int64

In [29]:
columns_to_use = [
    'income',
    'credit_risk_score',
    'customer_age',
    'payment_type',
    'employment_status',
    'current_address_months_count',
    'fraud_bool'  # Target variable
]
# Create a new DataFrame with only the specified columns
df_resample = balanced_df[columns_to_use]

In [30]:
display(df_resample)

,income,credit_risk_score,customer_age,payment_type,employment_status,current_address_months_count,fraud_bool
0,0.1,98,20,AC,CA,5,0
1,0.1,264,20,AC,CA,263,0
2,0.8,223,20,AB,CA,15,0
3,0.6,86,70,AB,CC,40,0
4,0.3,61,30,AC,CA,363,1
...,...,...,...,...,...,...,...
995,0.9,169,40,AC,CA,231,1
996,0.3,15,70,AD,CC,127,1
997,0.7,104,40,AD,CA,325,0
998,0.9,177,60,AC,CB,264,1
999,0.7,102,30,AA,CB,153,1

In [32]:
df_resample.to_csv(r'D:\Study\Kuliah Semester 5\Simulasi A2\Tugas Akhir\df_resample.csv', index=False)

Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "C:\Users\reyne\AppData\Roaming\Python\Python310\site-packages\IPython\core\interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\reyne\AppData\Local\Temp\ipykernel_17776\2203538725.py", line 1, in <module>
    df_resample.to_csv(r'D:\Study\Kuliah Semester 5\Simulasi A2\Tugas Akhir\df_resample.csv', index=False)
  File "c:\Users\reyne\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    raise TypeError(msg)
  File "c:\Users\reyne\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py", line 3720, in to_csv
    str or None
  File "c:\Users\reyne\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    raise TypeError(msg)
  File "c:\Users\reyne\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\formats\format.py", line 1162, in to_csv
  File "c:\Users\reyne\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\formats\csvs.py", line 24, in <module>
    from pandas._typing import SequenceNotStr
ImportError: cannot import name 'SequenceNotStr' from 'pandas._typing' (c:\Users\reyne\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\_typing.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\reyne\AppData\Roaming\Python\Python310\site-packages\IPython\core\interactiveshell.py", line 2057, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "C:\Users\reyne\AppData\Roaming\Python\Python310\site-packages\IPython\core\ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\Users\reyne\AppData\Roaming\Python\Python310\site-packages\IPython\core\ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "C:\Users\reyne\AppData\Roaming\Python\Python310\site-packages\IPython\core\ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "C:\Users\reyne\AppData\Roaming\Python\Python310\site-packages\IPython\core\ultratb.py", line 818, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "C:\Users\reyne\AppData\Roaming\Python\Python310\site-packages\IPython\core\ultratb.py", line 736, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "C:\Users\reyne\AppData\Roaming\Python\Python310\site-packages\stack_data\utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\reyne\AppData\Roaming\Python\Python310\site-packages\stack_data\core.py", line 734, in lines
    pieces = self.included_pieces
  File "C:\Users\reyne\AppData\Roaming\Python\Python310\site-packages\stack_data\utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\reyne\AppData\Roaming\Python\Python310\site-packages\stack_data\core.py", line 681, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "C:\Users\reyne\AppData\Roaming\Python\Python310\site-packages\stack_data\utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\reyne\AppData\Roaming\Python\Python310\site-packages\stack_data\core.py", line 660, in executing_piece
    return only(
  File "C:\Users\reyne\AppData\Roaming\Python\Python310\site-packages\executing\executing.py", line 190, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0